sudo: false
language: python
matrix:
    include:
        - python: 3.5
          env: TEST_MODE=UNIT_TESTS
        - python: 3.5
          env: TEST_MODE=INTEGRATION_TESTS
        - python: 3.5
          env: TEST_MODE=PEP8
    allow_failures:
        - python: 3.5
          env: TEST_MODE=INTEGRATION_TESTS
    fast_finish: true
install:
    - pip install pytest pytest-xdist pytest-cov python-coveralls coverage==3.7.1
    - pip install pep8 pytest-pep8
    - pip install -r requirements.txt
    - wget https://github.com/karoldvl/ESC-50/archive/wav-files.zip && unzip -q wav-files.zip -d data/ && mv data/ESC-50-wav-files data/ESC-50 && rm -f wav-files.zip
    - mkdir data/.ESC-50.cache
script:
    - if [[ "$TEST_MODE" == "INTEGRATION_TESTS" ]]; then
          PYTHONPATH=$PWD:$PYTHONPATH travis_wait 30 py.test tests/integration_tests --timeout=1200;
      elif [[ "$TEST_MODE" == "PEP8" ]]; then
          PYTHONPATH=$PWD:$PYTHONPATH py.test --pep8 -m pep8 -n0;
      elif [[ "$TEST_MODE" == "UNIT_TESTS" ]]; then
          PYTHONPATH=$PWD:$PYTHONPATH py.test tests/ --ignore=tests/integration_tests;
      fi
after_success:
    - coveralls